# Generated by Django 5.2.8 on 2026-01-02 18:21

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailcore', '0095_groupsitepermission'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('body', wagtail.fields.RichTextField(blank=True, verbose_name='Body')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SharksPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('sharks', wagtail.fields.StreamField([('shark_list', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the shark', 'label': '', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the shark', 'label': 'Image', 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Shark Detail Page', 'page_type': ['home.SharkPage'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('shark_page', 2)]], {}), 4: ('wagtail.blocks.ListBlock', (3,), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.RichTextField(blank=True, verbose_name='Body'),
        ),
        migrations.CreateModel(
            name='SharkPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('name', models.CharField(max_length=255, verbose_name='Name of the shark')),
                ('latin_name', models.CharField(max_length=255, verbose_name='Latin name')),
                ('size', models.CharField(max_length=255, verbose_name='Size')),
                ('conservation_status', models.CharField(choices=[('extinct', 'extinct'), ('extinct in the wild', 'extinct in the wild'), ('critical endangered', 'critical endangered'), ('endangered', 'endangered'), ('vulnerable', 'vulnerable'), ('near threatened', 'near threatened'), ('least concern', 'least concern')], default=('extinct', 'extinct'), max_length=100, verbose_name='Conservation status')),
                ('description', wagtail.fields.RichTextField(blank=True, verbose_name='Description')),
                ('image', models.ForeignKey(help_text='Image of the shark', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
