# Generated by Django 5.2.8 on 2026-01-12 19:33

import django.db.models.deletion
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_aboutpage_sharkspage_alter_homepage_body_sharkpage'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('quiz', wagtail.fields.StreamField([('question_list', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Question', 'label': '', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Response', 'label': '', 'required': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Is correct'}), 3: ('wagtail.blocks.StructBlock', [[('response', 1), ('is_correct', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('response', 3)]], {'label': 'Responses', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('question', 0), ('responses', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {})})),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
