# Generated by Django 5.2.8 on 2026-01-13 06:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_quizpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpage',
            name='quiz',
            field=wagtail.fields.StreamField([('question_list', 6)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Question', 'label': '', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Response', 'label': '', 'required': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Is correct', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('response', 1), ('is_correct', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('response', 3)]], {'label': 'Responses', 'required': True}), 5: ('wagtail.blocks.StructBlock', [[('question', 0), ('responses', 4)]], {}), 6: ('wagtail.blocks.ListBlock', (5,), {})}),
        ),
    ]
