# Generated by Django 5.2.8 on 2026-02-07 14:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_quizpage_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharkspage',
            name='sharks',
            field=wagtail.fields.StreamField([('shark_thumbnails', 3)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the shark', 'label': '', 'required': True}), 1: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the shark', 'label': 'Image', 'required': True}), 2: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Shark Detail Page', 'page_type': ['home.SharkPage'], 'required': True}), 3: ('wagtail.blocks.StructBlock', [[('name', 0), ('image', 1), ('shark_page', 2)]], {})}),
        ),
    ]
