# Generated by Django 5.2.8 on 2026-02-16 21:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_sharkspage_sharks'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpage',
            name='hero_bubble_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text wrapped into a blue bubble'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label of the cta'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_image',
            field=models.ForeignKey(help_text='Image of the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle of the page'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_bubble_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text wrapped into a blue bubble'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label of the cta'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(help_text='Image of the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle of the page'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_bubble_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text wrapped into a blue bubble'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label of the cta'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_image',
            field=models.ForeignKey(help_text='Image of the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle of the page'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_bubble_text',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Text wrapped into a blue bubble'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_cta_label',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label of the cta'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_image',
            field=models.ForeignKey(help_text='Image of the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_subtitle',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle of the page'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page'),
        ),
    ]
