# Generated by Django 5.2.8 on 2026-02-17 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_aboutpage_hero_bubble_text_aboutpage_hero_cta_label_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='quizpage',
            name='hero_title',
        ),
        migrations.RemoveField(
            model_name='sharkspage',
            name='hero_title',
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_blue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, blue part'),
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_title_white',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, white part'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_blue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, blue part'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title_white',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, white part'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_title_blue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, blue part'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_title_white',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, white part'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_title_blue',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, blue part'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_title_white',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Title of the page, white part'),
        ),
    ]
