# Generated by Django 5.2.8 on 2026-02-18 06:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_aboutpage_hero_title_and_more'),
        ('wagtailcore', '0095_groupsitepermission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutpage',
            name='hero_cta_label',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='hero_cta_label',
        ),
        migrations.RemoveField(
            model_name='quizpage',
            name='hero_cta_label',
        ),
        migrations.RemoveField(
            model_name='sharkspage',
            name='hero_cta_label',
        ),
        migrations.CreateModel(
            name='CallToAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('external_url', models.URLField(blank=True, help_text='Use this if linking to an external site instead of a page', verbose_name='External URL')),
                ('page', models.ForeignKey(blank=True, help_text='Internal page this CTA links to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.page', verbose_name='Page')),
            ],
            options={
                'verbose_name': 'Call to Action',
                'verbose_name_plural': 'Calls to Action',
            },
        ),
        migrations.AddField(
            model_name='aboutpage',
            name='hero_cta',
            field=models.ForeignKey(blank=True, help_text='Call to action button for the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.calltoaction', verbose_name='CTA'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_cta',
            field=models.ForeignKey(blank=True, help_text='Call to action button for the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.calltoaction', verbose_name='CTA'),
        ),
        migrations.AddField(
            model_name='quizpage',
            name='hero_cta',
            field=models.ForeignKey(blank=True, help_text='Call to action button for the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.calltoaction', verbose_name='CTA'),
        ),
        migrations.AddField(
            model_name='sharkspage',
            name='hero_cta',
            field=models.ForeignKey(blank=True, help_text='Call to action button for the hero', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.calltoaction', verbose_name='CTA'),
        ),
    ]
