# Generated by Django 5.2.8 on 2026-02-20 16:24

import home.snippets
import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_aboutpage_hero_image_alter_homepage_hero_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionHeader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='Subtitle')),
                ('eyebrow', models.CharField(blank=True, help_text='Small blue text above the main title', max_length=255, null=True, verbose_name='Eyebrow')),
            ],
            options={
                'verbose_name': 'Section Header',
                'verbose_name_plural': 'Section Headers',
            },
        ),
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section_header', 0)], block_lookup={0: ('wagtail.snippets.blocks.SnippetChooserBlock', (home.snippets.SectionHeader,), {})}),
        ),
    ]
