# Generated by Django 5.2.8 on 2026-02-24 07:14

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0014_alter_homepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizpage",
            name="body",
            field=wagtail.fields.StreamField(
                [("heading", 3)],
                blank=True,
                block_lookup={
                    0: ("wagtail.blocks.CharBlock", (), {"label": "Title"}),
                    1: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {"label": "Subtitle", "required": False},
                    ),
                    2: (
                        "wagtail.blocks.CharBlock",
                        (),
                        {
                            "help_text": "Small blue text above the main title",
                            "label": "Eyebrow",
                            "required": False,
                        },
                    ),
                    3: (
                        "wagtail.blocks.StructBlock",
                        [[("title", 0), ("subtitle", 1), ("eyebrow", 2)]],
                        {},
                    ),
                },
                null=True,
            ),
        ),
    ]
