# Generated by Django 5.2.8 on 2026-02-20 18:24

import home.snippets
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('section_header', 0)], block_lookup={0: ('home.blocks.SectionHeaderBlock', (home.snippets.SectionHeader,), {'required': False})}),
        ),
    ]
