# Generated by Django 5.2.8 on 2026-03-14 16:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_quizpage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizpage',
            name='quiz',
            field=wagtail.fields.StreamField([('question_list', 7)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Question', 'label': '', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': '', 'label': 'Option', 'required': True}), 2: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Is correct', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('option', 1), ('is_correct', 2)]], {}), 4: ('wagtail.blocks.StreamBlock', [[('option', 3)]], {'label': 'Possible options', 'required': True}), 5: ('wagtail.blocks.CharBlock', (), {'help_text': '', 'label': 'Correct answer', 'required': True}), 6: ('wagtail.blocks.StructBlock', [[('question', 0), ('options', 4), ('answer', 5)]], {}), 7: ('wagtail.blocks.ListBlock', (6,), {})}),
        ),
    ]
