# Generated by Django 5.2.8 on 2026-03-19 21:57

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_alter_quizpage_quiz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3), ('card_grid', 9), ('anatomy', 11)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small blue text above the main title', 'label': 'Eyebrow', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('eyebrow', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': '', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': '', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 1), ('link', 5), ('click_label', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('card', 7)]], {'label': 'Cards', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('cards', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('image', 10)]], {})}, null=True),
        ),
    ]
