# Generated by Django 5.2.8 on 2026-05-09 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_alter_homepage_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharkpage',
            name='distribution_map',
            field=models.TextField(blank=True, help_text='SVG code for the shark distribution map', verbose_name='Distribution map SVG'),
        ),
    ]
