# Generated by Django 5.2.8 on 2026-05-09 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_sharkpage_distribution_map'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, help_text='Brand description paragraph in the footer', verbose_name='Description')),
                ('copyright_text', models.CharField(blank=True, max_length=255, verbose_name='Copyright text')),
            ],
            options={
                'verbose_name': 'Footer',
                'verbose_name_plural': 'Footer',
            },
        ),
    ]
