# Generated by Django 5.2.8 on 2026-09-28 18:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0020_default_site_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.fields.StreamField([('heading', 3), ('card_grid', 9), ('anatomy', 11), ('shark_facts', 20)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'label': 'Title'}), 1: ('wagtail.blocks.CharBlock', (), {'label': 'Subtitle', 'required': False}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': 'Small blue text above the main title', 'label': 'Eyebrow', 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('title', 0), ('subtitle', 1), ('eyebrow', 2)]], {}), 4: ('wagtail.blocks.CharBlock', (), {'label': 'Title', 'required': True}), 5: ('wagtail.blocks.PageChooserBlock', (), {'label': '', 'required': True}), 6: ('wagtail.blocks.CharBlock', (), {'label': '', 'required': False}), 7: ('wagtail.blocks.StructBlock', [[('title', 4), ('subtitle', 1), ('link', 5), ('click_label', 6)]], {}), 8: ('wagtail.blocks.StreamBlock', [[('card', 7)]], {'label': 'Cards', 'required': True}), 9: ('wagtail.blocks.StructBlock', [[('cards', 8)]], {}), 10: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': True}), 11: ('wagtail.blocks.StructBlock', [[('title', 4), ('image', 10)]], {}), 12: ('wagtail.blocks.CharBlock', (), {'help_text': "Short and punchy, e.g. '400+', '1 in 3.7M' or 'Dermal denticles'", 'label': 'Key figure', 'max_length': 40, 'required': True}), 13: ('wagtail.blocks.CharBlock', (), {'help_text': "What the key figure is about, e.g. 'known shark species'", 'label': 'Caption', 'required': False}), 14: ('wagtail.blocks.TextBlock', (), {'help_text': 'Revealed when the card is hovered or focused', 'label': 'Description', 'required': False}), 15: ('wagtail.images.blocks.ImageChooserBlock', (), {'label': 'Image', 'required': False}), 16: ('wagtail.blocks.URLBlock', (), {'label': 'Source', 'required': False}), 17: ('wagtail.blocks.BooleanBlock', (), {'help_text': 'Make the card span two columns to put the fact forward', 'label': 'Wide card', 'required': False}), 18: ('wagtail.blocks.StructBlock', [[('highlight', 12), ('caption', 13), ('description', 14), ('image', 15), ('source', 16), ('wide', 17)]], {}), 19: ('wagtail.blocks.ListBlock', (18,), {'label': 'Facts', 'min_num': 1}), 20: ('wagtail.blocks.StructBlock', [[('facts', 19)]], {})}, null=True),
        ),
    ]
