# Generated by Django 5.2.8 on 2026-10-03 19:46

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0021_shark_facts_block'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sharkspage',
            name='sharks',
            field=wagtail.fields.StreamField([('shark_thumbnails', 4)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'help_text': 'Name of the shark', 'label': '', 'required': True}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'Latin name of the species, e.g. Prionace glauca', 'label': 'Scientific name', 'required': False}), 2: ('wagtail.images.blocks.ImageChooserBlock', (), {'help_text': 'Image of the shark', 'label': 'Image', 'required': True}), 3: ('wagtail.blocks.PageChooserBlock', (), {'label': 'Shark Detail Page', 'page_type': ['home.SharkPage'], 'required': True}), 4: ('wagtail.blocks.StructBlock', [[('name', 0), ('scientific_name', 1), ('image', 2), ('shark_page', 3)]], {})}),
        ),
    ]
